[package]
name = "lean-tidy"
version = "0.1"
lean_version = "khoek/klean:3.4.4"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "891dfbbebba8a0269072460785172c294935af22"}
libk = {git = "https://github.com/khoek/libk", rev = "461caf0b2915dd612a5e9f4ad7f6b627506d4ec0"}
